pluginManagement {
  plugins {
    id 'org.openjfx.javafxplugin' version "${javafxPluginVersion}"
    id 'org.springframework.boot' version "${springFrameworkVersion}"
    id 'io.spring.dependency-management' version "${springDependencyVersion}"
  }
}

rootProject.name = 'DepanFX'

include 'DepanFxApp'
include 'DepanFxBytecode'
include 'DepanFxFileSystem'
include 'DepanFxFileSystemGui'
include 'DepanFxFileSystemNodeView'
include 'DepanFxGraph'
include 'DepanFxGit'
include 'DepanFxGitGui'
include 'DepanFxGraphDoc'
include 'DepanFxJava'
include 'DepanFxJavaGui'
include 'DepanFxJavaNodeView'
include 'DepanFxNodeFilters'
include 'DepanFxNodeFiltersGui'
include 'DepanFxNodeList'
include 'DepanFxNodeListGui'
include 'DepanFxJavaXstream'
include 'DepanFxJogl'
include 'DepanFxNodeList'
include 'DepanFxNodeListGui'
include 'DepanFxNodeListViewer'
include 'DepanFxNodeViewData'
include 'DepanFxNodeViewGui'
include 'DepanFxPersistence'
include 'DepanFxPerspective'
include 'DepanFxScene'
include 'DepanFxSession'
include 'DepanFxSessionData'
include 'DepanFxWorkspace'
include 'DepanFxWorkspaceGui'
