plugins {
  id 'depanfx.base'
  id 'org.openjfx.javafxplugin'
  id 'org.springframework.boot'
  id 'io.spring.dependency-management'
}

javafx {
  version = "${javafxVersion}"
  modules = [ 'javafx.controls', 'javafx.fxml' ]
}

dependencies {
  implementation 'org.springframework.boot:spring-boot-autoconfigure'
  implementation "net.rgielen:javafx-weaver-core:${javafxWeaverVersion}"
  implementation "org.apache.commons:commons-csv:${apacheCsv}"

  implementation "com.pnambic.modxstream:modxstream:${modxstreamVersion}"

  implementation project(':DepanFxBase')
  implementation project(':DepanFxGraph')
  implementation project(':DepanFxGraphDoc')
  implementation project(':DepanFxGraphInfo')
  implementation project(':DepanFxJogl')
  implementation project(':DepanFxNodeFilters')
  implementation project(':DepanFxNodeFiltersGui')
  implementation project(':DepanFxNodeList')
  implementation project(':DepanFxNodeListGui')
  implementation project(':DepanFxNodeViewData')
  implementation project(':DepanFxPersistence')
  implementation project(':DepanFxPerspective')
  implementation project(':DepanFxScene')
  implementation project(':DepanFxSessionData')
  implementation project(':DepanFxWorkspace')
}
