import java.text.SimpleDateFormat

plugins {
  id 'depanfx.base'
  id 'org.openjfx.javafxplugin'
  id 'org.springframework.boot'
  id 'io.spring.dependency-management'
  id 'application'
  id 'org.beryx.jlink' version "${beryxJlinkVersion}"
}

javafx {
  version = "20"
  modules = [ 'javafx.controls', 'javafx.fxml' ]
}

dependencies {
  implementation 'org.springframework.boot:spring-boot-starter'
  implementation 'org.springframework.boot:spring-boot-autoconfigure'
  implementation "net.rgielen:javafx-weaver-core:${javafxWeaverVersion}"

  implementation project(':DepanFxBytecode')
  implementation project(':DepanFxFileSystem')
  implementation project(':DepanFxFileSystemGui')
  implementation project(':DepanFxFileSystemNodeView')
  implementation project(':DepanFxGit')
  implementation project(':DepanFxGitGui')
  implementation project(':DepanFxGraph')
  implementation project(':DepanFxGraphDoc')
  implementation project(':DepanFxJava')
  implementation project(':DepanFxJavaGui')
  implementation project(':DepanFxJavaNodeView')
  implementation project(':DepanFxNodeListGui')
  implementation project(':DepanFxNodeListViewer')
  implementation project(':DepanFxNodeViewGui')
  implementation project(':DepanFxPersistence')
  implementation project(':DepanFxPerspective')
  implementation project(':DepanFxScene')
  implementation project(':DepanFxSession')
  implementation project(':DepanFxSessionData')
  implementation project(':DepanFxWorkspace')
  implementation project(':DepanFxWorkspaceGui')

  // Cross platform "fat" jar
  runtimeOnly "org.openjfx:javafx-base:$javafx.version:win"
  runtimeOnly "org.openjfx:javafx-base:$javafx.version:linux"
  runtimeOnly "org.openjfx:javafx-base:$javafx.version:mac"
  runtimeOnly "org.openjfx:javafx-controls:$javafx.version:win"
  runtimeOnly "org.openjfx:javafx-controls:$javafx.version:linux"
  runtimeOnly "org.openjfx:javafx-controls:$javafx.version:mac"
  runtimeOnly "org.openjfx:javafx-fxml:$javafx.version:win"
  runtimeOnly "org.openjfx:javafx-fxml:$javafx.version:linux"
  runtimeOnly "org.openjfx:javafx-fxml:$javafx.version:mac"
  runtimeOnly "org.openjfx:javafx-graphics:$javafx.version:win"
  runtimeOnly "org.openjfx:javafx-graphics:$javafx.version:linux"
  runtimeOnly "org.openjfx:javafx-graphics:$javafx.version:mac"

  testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

application {
  mainClass = "com.pnambic.depanfx.DepanFxApplication"
  mainModule = "depanfx.app"
  applicationDefaultJvmArgs = [
    '-Xmx4G',
    '--add-opens', 'javafx.graphics/com.sun.javafx.tk=ALL-UNNAMED',
    '--add-opens', 'javafx.graphics/javafx.stage=ALL-UNNAMED',
    '--add-opens', 'javafx.graphics/com.sun.javafx.tk.quantum=ALL-UNNAMED',
    '--add-opens', 'javafx.graphics/com.sun.glass.ui=ALL-UNNAMED'
  ]
}

// Create a build info file
task buildInfo {
    doLast {
        // Get the current date
        def currentDate = new Date()
        def dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm Z")
        def buildDate = dateFormat.format(currentDate)

        // Get the release number (assuming you're using a versioning scheme like SemVer)
        def releaseTag = System.getenv("BUILD_REF") ?: "-dev-"
        def releaseNumber = project.version

        // Get the Git SHA-1 and modifications summary
        def gitSha = 'git rev-parse --short HEAD'.execute().text.trim()
        def gitMods = 'git diff --stat'.execute().text.split("\n")
        def modSummary = gitMods[-1].trim()
        if (modSummary.isEmpty()) {
            modSummary = "-clean-"
        }

        // Construct the build info property file
        def buildInfoFile = new File(buildDir,
            "resources/main/com/pnambic/depanfx/app/build-info.properties")
        def buildInfoWriter = buildInfoFile.newPrintWriter()

        buildInfoWriter.println("date=$buildDate")
        buildInfoWriter.println("tag=$releaseTag")
        buildInfoWriter.println("release=$releaseNumber")
        buildInfoWriter.println("sha1=$gitSha")
        buildInfoWriter.println("mods=$modSummary")
        buildInfoWriter.close()
    }
}

// Overwrite any build info resouce copied from the source tree
buildInfo.dependsOn classes

// Prepare the build info resouce before any further progress
jar.dependsOn buildInfo

jlink {
  options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
  launcher {
    name = 'depanfx'
  }
}
